version: "3.3"
services:
  mariadb:
    hostname: mariadb
    environment:
      - TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=${mysql_root_pass}
      - MYSQL_DATABASE=${mysql_database}
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
#      - MYSQL_ONETIME_PASSWORD=yes
    volumes:
      - ./data:/config
    restart: always
    image: lscr.io/linuxserver/mariadb

  zabbix-server-mysql:
        hostname: zabbix-server-mysql
        environment:
            - DB_SERVER_HOST=mariadb
            - MYSQL_USER=${mysql_user}
            - MYSQL_PASSWORD=${mysql_password}
            - MYSQL_DATABASE=${mysql_database}
        restart: always
        image: zabbix/zabbix-server-mysql
        depends_on:
            - mariadb

  zabbix-web-nginx-mysql:
        hostname: zabbix-web-nginx-mysql
        environment:
            - DB_SERVER_HOST=mariadb
            - MYSQL_USER=${mysql_user}
            - MYSQL_PASSWORD=${mysql_password}
            - MYSQL_DATABASE=${mysql_database}
            - ZBX_SERVER_HOST=zabbix-server-mysql
            - PHP_TZ=Europe/Madrid
        ports:
            - 8080
            - 8443
            - 80
        restart: always
        image: zabbix/zabbix-web-nginx-mysql
        depends_on:
            - mariadb
            - zabbix-server-mysql

#  zabbix-agent:
#    hostname: some-zabbix-agent
#    privileged: true
#    environment:
#      - ZBX_HOSTNAME=some-hostname
#      - ZBX_SERVER_HOST=zabbix-server-mysql
#    image: zabbix/zabbix-agent
#    depends_on:
#      - zabbix-server-mysql
